### ISSUE TITLE
[tracking] ZeroVec improvements

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1082]
We have a whole bunch of ZeroVec improvements we want to do, this issue exists to track them.

:star:'d entries are planned for Q4 2021, the rest are "nice to have" and not currently planned with any specific target

 - [x] :star: https://github.com/unicode-org/icu4x/pull/1065 
    - [x] :star: https://github.com/unicode-org/icu4x/issues/1078 (needed by @zbraniecki  for #615)
        - [x] :star: https://github.com/unicode-org/icu4x/issues/1179 (not needed super strongly just yet)
           - [x] :star: https://github.com/unicode-org/icu4x/pull/1173 (needed by @zbraniecki for DTF)
           - [x] :star: https://github.com/unicode-org/icu4x/pull/1199
        - [x] :star: https://github.com/unicode-org/icu4x/issues/676 (needed by @sffc for #1056) sub-issues:
            - [x] :star: `VarZeroVecBorrowed` https://github.com/unicode-org/icu4x/pull/1223
              - [x] https://github.com/unicode-org/icu4x/issues/1228
            - [x] <s>`ZeroVecBorrowed`</s> Deemed unnecessary for now
            - [x] :star: `ZeroMapBorrowed` https://github.com/unicode-org/icu4x/pull/1238
              - [x] Cleanup: https://github.com/unicode-org/icu4x/issues/1247
        - [x] https://github.com/unicode-org/icu4x/issues/1079 
          - [x] Depends on https://github.com/unicode-org/icu4x/pull/1389
          - [ ] https://github.com/unicode-org/icu4x/pull/1642
          - [ ] https://github.com/unicode-org/icu4x/issues/1258
    - [x] :star: https://github.com/unicode-org/icu4x/issues/1080
  - [ ] https://github.com/unicode-org/icu4x/issues/1081
  - [x] :star: https://github.com/unicode-org/icu4x/issues/1083 (PR at https://github.com/unicode-org/icu4x/pull/1103)
  - [x] :star: https://github.com/unicode-org/icu4x/pull/1094
  - [x] https://github.com/unicode-org/icu4x/issues/1144
  - [x] :star:  https://github.com/unicode-org/icu4x/issues/1184
    - [x] https://github.com/unicode-org/icu4x/issues/1260
  - [x] https://github.com/unicode-org/icu4x/issues/1180
  - [x] https://github.com/unicode-org/icu4x/issues/1261
  - [x] https://github.com/unicode-org/icu4x/issues/1367
  - [x] https://github.com/unicode-org/icu4x/pull/1418
  - [x] https://github.com/unicode-org/icu4x/issues/1475
    - [x] contains: https://github.com/unicode-org/icu4x/issues/1190
  - [ ] https://github.com/unicode-org/icu4x/issues/1443

cc @sffc @zbraniecki

**Comment by Manishearth** [comment]
The items planned for the 0.5 milestone were completed, removing the tracking issue from the milestone. Everything else is mostly a "nice to have"

**Comment by Manishearth** [comment]
There's still work to be done here but the initial set of planned things is done including all stretch items and I don't think we need this megaissue anymore.
