### ISSUE TITLE
User-Friendly Data Slicing

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1110]
This is the meta-issue to track tasks relating to user-friendly slicing of ICU4X locale data.

- [x] #948 -- the primary mechanism for us to perform data slicing
    - [x] #1106 -- prerequisite
- [ ] ~#1108 (Stretch for Q4) -- a secondary option that may be more versatile~ (deprioritized)
- [x] #1107 -- required for loading data in smaller chunks
- [x] #718 -- required for user-friendly toolchain automation
    - [x] #1105 -- prerequisite
    - [x] #455 -- follow-up
- [ ] #664

More sub-tasks may be added as work progresses.

**Comment by sffc** [comment]
The last remaining issue is #664. Closing in favor of that issue.
