### ISSUE TITLE
Support Temporal

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#1174]
We will be supporting many pieces of code required to implement Temporal, in particular the time zone and calendrical calculations.  We need to decide how we will expose a Temporal-compatible API in Rust and/or JavaScript.

**Comment by sffc** [comment]
I thought we had this conversation going somewhere else, but I couldn't find it, so I'll start it fresh here.

I made a little flow chart of calendar-dependent operations in the Temporal spec:

<img width="4485" height="1608" alt="Image" src="https://github.com/user-attachments/assets/c61e4348-9c00-4d2c-a8c5-2232688beec7" />

CalendarHasMidYearEras is coming in https://github.com/tc39/proposal-intl-era-monthcode/pull/77.

I plan to make functions in ICU4X implementing each one of the five lavender-colored bubbles in that diagram, and one mega function to implement the orange-colored bubbles (described in https://github.com/unicode-org/icu4x/issues/6790#issuecomment-3198939624).

Possible API for the left two lavender bubbles:

```rust
#[non_exhaustive]
pub struct CalendarEraInfo {
    supports_eras: boolean,
    has_mid_year_eras: boolean,
}

trait Calendar {
    // new trait function. question: should it take &self?
    fn era_info() -> CalendarEraInfo;
}
```

CalendarISOToDate is already supported with Date::new_from_iso.

CalendarDateAdd is already partially implemented by the doc-hidden [Date::add](https://github.com/unicode-org/icu4x/blob/c1cfbf8cb41d7a703188374985d550b6c2bda296/components/calendar/src/date.rs#L195), but I am thinking of changing it in a few ways:

1. Remove the type parameter from DateDuration
2. Make the DateDuration have unsigned fields plus a single sign bit
3. Add an _overflow_ option to Date::add
4. _Maybe_ remove the `weeks` fields since Temporal says it is always identical to 7 days
5. _Maybe_ rename some things along the way

Adjustments to Date::until:

1. Remove smallest_unit. The Temporal spec only passes largest_unit into this AO and handles smallest_unit in a rounding function that is separate from the calendar-dependent part (one that ends up calling back into Date::add).
2. Hmm, since largest_unit could be weeks, maybe I should leave `weeks` in DateDuration.

Does this API surface (what sits between ICU4X and Temporal_rs or SpiderMonkey) make sense to everyone?

@Manishearth @nekevss @anba @ptomato

**Comment by nekevss** [comment]
The overview and general API makes sense to me. My initial reaction for the trait function is that it should take `&self`. CalendarDateAdd 1-3 sounds good to me as well.

My preference would be a `weeks` field on the `DateDuration` to be present but that could ultimately be worked around if you decide to go without the field.

**Comment by Manishearth** [comment]
The general API here looks good to me. I think keeping weeks around makes the most sense because of the unit issue. Presumably clients can rebalance that if they really need, but it's an ugly separation of concerns.

**Comment by sffc** [comment]
How big of an integer should the DateDuration fields be?

From https://tc39.es/proposal-temporal/#sec-isvalidduration, it looks like years, months, and weeks can all be `u32`. Days though is bounded by `days × 86,400 < 2^53`, which is more than 2^32.

It appears that Temporal_rs uses i64 for the public fields. I think ICU4X should be stricter because this is an input type and I don't want to have to validate that the fields all share the same sign.

**Comment by nekevss** [comment]
I'm forgetting the exact number but days could be contained in a `U40` if it were desired to compact to that degree, but the inner DateDuration, which is more computation focused, ends up being a `i64` / `u64`.

**Comment by sffc** [comment]
`Date::add` needs to return a `Result` since it can reject (in `Overflow::Reject`), but the operation should be infallible if in constraining mode. It would be nice for users of ICU4X to export an infallible fn.

Should I make the Result-returning one called `Date::add_with_options` for now so that we could potentially add a function with another signature later?

**Comment by Manishearth** [comment]
I'm fine with a single function but I think add_with_options is ok too.

**Comment by sffc** [comment]
To-do items from #7012:

- [ ] Graduate the APIs and bikeshed them a bit more. Perhaps make the fields of DateDuration be private. https://github.com/unicode-org/icu4x/issues/3964
- [ ] Add fast paths for adding multiple days, months, or years at once https://github.com/unicode-org/icu4x/issues/7077
- [ ] Add more tests on algorithm behavior, such as Hebrew tests in the backwards direction
- [ ] Add more tests on constrain/reject behavior and edge cases (constrain should never fail)

**Comment by sffc** [comment]
Tests are tracked in https://github.com/unicode-org/icu4x/issues/7078.

Given that V8 is now implementing Temporal with ICU4X, I'm going to mark this issue as Fixed.
