### ISSUE TITLE
API for accessing Unicode properties

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#148]
Sub-issues:

- [x] https://github.com/unicode-org/icu4x/issues/1070
- [x] https://github.com/unicode-org/icu4x/issues/1071
- [x] https://github.com/unicode-org/icu4x/issues/1072
- [x] https://github.com/unicode-org/icu4x/issues/1073
- [x] https://github.com/unicode-org/icu4x/issues/1074
- [x] https://github.com/unicode-org/icu4x/issues/936

---

With UnicodeSet (#91) and UCPTrie (#132) coming along, we should start thinking about what the API will look like for accessing Unicode properties.

A simple and clean solution would be a bunch of functions returning either UnicodeSet or UCPTrie, such as:

```rust
// Binary Unicode property
pub fn get_whitespace_set() -> Result<UnicodeSet, Error>;

// Enumerated Unicode property
pub fn get_digits_trie() -> Result<UCPTrie, Error>;
```

These functions would pull from the data provider.  The data provider produces serialized sets or tries, and these functions are pretty thin wrappers that convert the serialized format to a Rust UnicodeSet or UCPTrie.

Thoughts?

@markusicu @macchiati @srl295 @EvanJP

**Comment by sffc** [comment]
@kpozin suggested that we could also have an API on `char`, similar to `toLocaleString()`.  It might be more convenient when getting a property for a single character.

**Comment by aethanyc** [comment]
@echeran I'm looking for the API to query the line break property value given a codepoint, e.g. `f(codepoint, line_break_property) -> line_break_property_value`, and investigating if it's possible to replaced the API currently used in line breaker. 

https://github.com/unicode-org/icu4x/blob/cd4b7c536c0b573aa68510bc8e1776fa78b1c0fd/experimental/segmenter/src/line_breaker.rs#L72-L76

Is this issue tracking the implementation of such an API?

**Comment by sffc** [comment]
> Is this issue tracking the implementation of such an API?

Yes.

**Comment by aethanyc** [comment]
Does this issue depend on  #883?

**Comment by sffc** [comment]
> Does this issue depend on #883?

In part, but the non-binary enumerated property API you are requesting above needs additional work.

**Comment by aethanyc** [comment]
Other than line breaker property, #943 also needs this API to map code point to various Unicode properties like Word_Break, Grapheme_Cluster_Break, etc.

**Comment by sffc** [comment]
I added a list of sub issues to the OP.

**Comment by sffc** [comment]
All six parts of this issue are done!  Closing as fixed.
