### ISSUE TITLE
Meta-issue: 0.5 Release

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#1546]
This issue exists to track the 0.5 release

Blockers:

 - [x] https://github.com/unicode-org/icu4x/pull/1545
 - [x] https://github.com/unicode-org/icu4x/pull/1529
 - [x] https://github.com/unicode-org/icu4x/pull/1556
 - [x] https://github.com/unicode-org/icu4x/pull/1547
 - [x] Birds eye view of coverage/docs/etc
 - [x] Final check with component owners
 - [x] Final check that no utils have had changes since release
 - [ ] Releasing components https://github.com/unicode-org/icu4x/pull/1562

**Comment by Manishearth** [comment]
Tracking various utils:

  - codepointtrie: 0.3.0, from 697526743
    - New APIs only, minor bump
 - deduplicating_array: New component, needs first publish
 - fixed_decimal: 0.2.1, from 09d5aef92
     - New APIs only, minor bump 
 - litemap
 - pattern
 - uniset
 - writeable
 - yoke
 - zerovec
