### ISSUE TITLE
Meta-issue: 0.6 Release

### ISSUE THREAD

**Issue by dminor** [unicode-org/icu4x#1861]
This issue exists to track the 0.6 release

Blockers:
 - [x] Birds eye view of coverage/docs/etc
 - [x] Final check with component owners
 - [x] Final check that no utils have had changes since release

**Comment by dminor** [comment]
Tracking various utils:

 - codepointtrie: 0.4.0, from c83c90c05314e7334a96f34abaca4bf7f0ab1bf3. API change in 29a3028dd12bd1787609c7b62626056422597284, major bump
 - crlify: New component, needs first publish
 - deduplicating_array: 0.1.1, from c83c90c05314e7334a96f34abaca4bf7f0ab1bf3, internal changes for linting only, minor bump
 - fixed_decimal: 0.3.0, from 4d98ad781a6b2473217de5f43236ee7b7ecfd205. API change in d9756b8bf21515807c6ce920db800884ef06e3c5, major bump
 - litemap: 0.2.2, 4d98ad781a6b2473217de5f43236ee7b7ecfd205. New APIs only, but we didn't do a major bump last time, think we should this time. 
 - pattern: 0.1.2, 6975267434af46fc4ec70fc7c7459a2bc74c2699. internal changes for linting only, minor bump
 - uniset: 0.5.0 4d98ad781a6b2473217de5f43236ee7b7ecfd205, renamed a feature, major bump
 - writeable: 0.5.0, from 4d98ad781a6b2473217de5f43236ee7b7ecfd205, API changed, major bump
 - yoke: 0.5.0, a52b2f6c2fef2fbaf22aa3b3aec56ac97f3ac42d. Unchanged from bump to 0.5.0
 - yoke-derive: 0.5.0, from a52b2f6c2fef2fbaf22aa3b3aec56ac97f3ac42d, Unchanged from bump to 0.5.0
 - zerofrom: 0.1.0, new component, needs first publish
 - zerovec: 0.7.0, from 4d98ad781a6b2473217de5f43236ee7b7ecfd205, API changed, major bump

**Comment by Manishearth** [comment]
> * zerofrom: 0.1.0, new component, needs first publish

It's already published

also, we probably need to do crabbake too

The rest looks right

**Comment by dminor** [comment]
@Manishearth crabbake is still in experimental... should we move it to utils and then publish it?

**Comment by Manishearth** [comment]
Yes

**Comment by Manishearth** [comment]
Actually, don't yet since there are PRs changing it. Just publish it from experimental/, we already do that for a bunch of crates

**Comment by dminor** [comment]
Crabbake will be 0.4.0, we've published a 0.1.0 to reserve the name

**Comment by Manishearth** [comment]
Note for the future: we shouldn't tag a release until everything is published since there's a slight chance failures in `cargo publish` (e.g. if the versions don't match up just right) require further commits), and tags are permanent.

Cargo publish does have a `--dry-run` mode but unfortunately it does not work at the workspace level — you cannot get it to do a dry run "assuming all dependent crates in this workspace have been published"

**Comment by eugenesvk** [comment]
I think the dependency version in the [intro.md](https://github.com/unicode-org/icu4x/blob/main/docs/tutorials/intro.md) tutorial should be update to `0.6` once the crate is published, currently it's `0.2`:
```rs
[dependencies]
icu = "0.2"
```

I was doing this tutorial and was puzzled why I was getting errors importing `icu::locid::locale` as stated in the example in [chapter 4](https://github.com/unicode-org/icu4x/blob/main/docs/tutorials/intro.md#4-accessing-components) and then realized that this macro only appeared in the version `0.6`, but this version isn't yet published at crates.io (and maybe the import command should change to `icu::locid::macros::locale`?)

**Comment by Manishearth** [comment]
Is everything done here?

**Comment by dminor** [comment]
Released https://github.com/unicode-org/icu4x/releases/tag/icu%400.6.0
