### ISSUE TITLE
Review ICU4X docs, public APIs, etc.

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#213]
When releasing v0.1, we should do a thorough review of all ICU4X APIs:

- [x] Make sure they are documented correctly
- [x] Check that the error code naming is consistent with the style guide
- [ ] Implement std::error::Error for all error codes
- [ ] Check that `#[non_exhaustive]` is used where required
- [x] Check the README files in the repo

**Comment by zbraniecki** [comment]
I'm punting this to 0.2 due to lack of time. We have done some of it, but things like decisions about errors (impl std::error::Error for all error types) and `non_exhaustive` will have to wait.

**Comment by zbraniecki** [comment]
Actually, it's a cleanup material.

**Comment by sffc** [comment]
I unchecked the two boxes you checked in the OP:

1. We are still inconsistent with error code naming. For example, sometimes we append "Error" to the enum entry and sometimes we don't.
2. Each component has a stub README. We should either delete those files or populate them with something meaningful.

**Comment by zbraniecki** [comment]
Thank you. I'll work on those and try to get as much as I can into 0.1

**Comment by zbraniecki** [comment]
I verified that no `Error` variants have that postfix.

**Comment by zbraniecki** [comment]
I started looking into this, and as for implementation of `std::error::Error`, I think we should focus on #213.

**Comment by zbraniecki** [comment]
This is the list of places where we use `non_exhaustive`:

```
icu4x/(errors)$ rg -A2 -t 'rust' 'non_exhaustive' ./
./components/provider_cldr/src/error.rs
11:#[non_exhaustive]
12-#[derive(Debug)]
13-pub enum Error {

./components/provider_cldr/src/cldr_paths.rs
35:#[non_exhaustive]
36-#[derive(Debug, PartialEq)]
37-pub struct CldrPathsLocal {

./components/provider_fs/src/manifest.rs
10:#[non_exhaustive]
11-#[derive(Copy, Clone, Debug, PartialEq, Serialize, Deserialize)]
12-pub enum AliasOption {
--
20:#[non_exhaustive]
21-#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
22-pub enum LocalesOption {
--
29:#[non_exhaustive]
30-#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
31-pub enum SyntaxOption {
--
52:#[non_exhaustive]
53-#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
54-pub(crate) struct Manifest {

./components/provider_fs/src/export/fs_exporter.rs
18:#[non_exhaustive]
19-#[derive(Copy, Clone, Debug, PartialEq, Serialize, Deserialize)]
20-pub enum OverwriteOption {
--
30:#[non_exhaustive]
31-#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
32-pub struct ExporterOptions {

./components/provider_fs/src/export/serializers/json.rs
10:#[non_exhaustive]
11-#[derive(Copy, Clone, Debug, PartialEq)]
12-pub enum StyleOption {
--
26:#[non_exhaustive]
27-#[derive(Clone, Debug, PartialEq)]
28-pub struct Options {

./components/provider/src/data_key.rs
14:#[non_exhaustive]
15-#[derive(PartialEq, Eq, Copy, Clone, Debug)]
16-pub enum DataCategory {

./components/provider_fs/src/export/serializers/bincode.rs
20:#[non_exhaustive]
21-#[derive(Clone, Debug, PartialEq)]
22-pub struct Options {}

./components/provider/src/error.rs
9:#[non_exhaustive]
10-#[derive(Debug)]
11-pub enum Error {
```

It seems to be consistent with our guidelines to me. @sffc - do you see anything that requires cleanup here?

**Comment by sffc** [comment]
> It seems to be consistent with our guidelines to me. @sffc - do you see anything that requires cleanup here?

There are a number of types that should definitely have the annotation that don't have it yet:

- ParserError
- PluralRulesError
- UnicodeSetError
- etc.

However, there are other types missing the annotation where the preferred result is not clear.

- PluralCategory
- PluralRuleType
- UnicodeSetSpanCondition
- LanguageIdentifier
- etc.

In my mind, we should use `#[non_exhaustive]` *by default, unless* we decide that a certain API should not have it.  Some reasons might include:

- An enum that is useful to be used in a match statement (perhaps PluralRuleType)
- An enum that is backed by a long-lived, stable specification (perhaps PluralCategory)
- A struct that is backed by a long-lived, stable specification (perhaps LanguageIdentifier)

However, for the sake of closing out this issue, I'm happy to follow up with this in #170.  It's not a good use of time to track down these cases before we have a CI tool to enforce it and prevent backsliding.

**Comment by zbraniecki** [comment]
Hmm, I think I'm confused about your approach to `non_exhaustive`. You seem to say that you are certain that all public errors should have it. Why? If we modify that enum we'll have a breaking release, and I don't think it's any different from changing other public APIs.

If we add it on public errors then we lose the chance to let user know that their error handling should be updated to handle new set of errors that may be returned by the public APIs.

Should I open an issue to discuss the use of non_exhaustive now that we have code that we can evaluate against it? :)

**Comment by sffc** [comment]
> If we modify that enum we'll have a breaking release, and I don't think it's any different from changing other public APIs.

The whole point of `non_exhaustive` is to avoid breaking changes when adding fields to structs and enums.  The way I see it is, after we release version 1.0.0, the bar for us to release 2.0.0 should be *extremely* high.  Certainly no more than once a year, but hopefully even less frequently than that, like once every 3 years.  I am strongly of the opinion that breaking changes are very costly to the ecosystem and we should go out of our way to avoid them.

However, your point about informing users of new error types is interesting.

Yeah, we can discuss in a follow-up issue.

**Comment by sffc** [comment]
Follow-up for non_exhaustive: #383

No remaining issues, so closing.
