### ISSUE TITLE
ICU4X 1.0 release checklist

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#2653]
- [ ] 1.0-final milestone empty
 - [ ] Casemapping and segmenter should not get 1.0 released
 - [x] Utils released (#2651, #2652)
 - [ ] Regular release checklist https://github.com/unicode-org/icu4x/blob/main/docs/process/release.md
 - [ ] Release all other crates
 - [ ] Blog post published
 - [ ] Email to icu4x-announce (posted from an @unicode.org email)

cc @sffc

**Comment by sffc** [comment]
npm is tracked in https://github.com/unicode-org/icu4x/issues/1175
