### ISSUE TITLE
2.0 cleanup list

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#2856]
* [x] Unreadable inversion list JSON deserialization (#2855)
* [x] Remove support for legacy collator naming (`sv_reformed_meta.toml`)
* [x] Remove `any.rs` from databake provider generated code
* [x] Remove the definition of `BakedDataProvider`, instead favoring direct invocation of the macros (may need discussion)
* [x] Remove `icu_datagen/legacy_api`
    * [x] Remove extra segmenter data from icu_datagen (#3003)
* [x] `CPT::get_ranges_for_value` should be `iter_ranges_for_value`
* [x] `TrieValue::to_u32()` should not be default-impl'd
* [x] make properties set/map/script/etc from_data private or hidden
* [x] Remove the `icu_datetime_experimental` feature from the `icu` metacrate (#3094)
* [x] https://github.com/unicode-org/icu4x/issues/3573
* [x] DateTimeFormat symbols data:
   * [x] https://github.com/unicode-org/icu4x/issues/3599
   * [x] https://github.com/unicode-org/icu4x/issues/3598
   * [ ] Should also consider splitting along symbol type
* [x] calendar year/month methods:
  * [x] Methods for getting formattable month/year should be called as such
  * [x] FormattableYear should use NonZeroU8 for cyclic
  * [x] FormattableMonth should consider dropping `ordinal` or using something else. 
* [x] Japanese's `try_new_date/time()` should have a `_with_calendar()` and another baked version should be added that doesn't need the calendar parameter.
* [x] Find any `#[deprecated]` functions and remove them
* [x] Remove mutable method on `Ethiopic`, potentially split calendar types https://github.com/unicode-org/icu4x/pull/6026
* [x] Make capi baked data constructors the "normal" ones
* [x] Upgrade to regex automata 0.3 (https://github.com/unicode-org/icu4x/pull/3655, #5130)
* [x] RangeBounds references: https://github.com/unicode-org/icu4x/issues/3678
* [x] Make `icu4x-datagen` CLI `--fallback` default to `Auto`
* [x] FFI
  * [x] Move everything to HIR
  * [x] Move everything to renamed namespaced APIs
  * [ ] https://github.com/unicode-org/icu4x/issues/3791
  * [x]  #3851
* [x] Encapsulate `DataKeyMetadata::{fallback_priority, extension_key, fallback_supplement}` in a `DataKeyMetadata::fallback_config` 
* [x] Consider making AbstractSerializer not use trait objects for the FsExporter in datagen https://github.com/unicode-org/icu4x/pull/6025, https://github.com/unicode-org/icu4x/pull/6263
* [ ] Fix name of `DateTimeError::UnsupportedField`
* [x] Remove variants of `DateTimeError` that are unused, such as Format
* [x] Stop exporting `icu_datetime::CldrCalendar` or mark it as "not intended to be implemented"
* [x] Delete `strict_cmp_iter` and `SubtagOrderingResult` in icu_locid (and any other deprecated APIs)

**Comment by Manishearth** [comment]
- make properties set/map/script/etc from_data private or hidden

**Comment by Manishearth** [comment]
Properties cleanups:

We should remove all of the free functions:

 - Binary property functions should go on CodePointSetData or whatever
 - Enumerated property functions should live on the relevant property

**Comment by Manishearth** [comment]
The only leftover items are

 - Make icu4x-datagen CLI --fallback default to Auto
   - We don't have this parameter anymore. @robertbastian ? We do have a `Fallback` enum in icu4x-datagen but it appears to not be used??
 - Fix name of DateTimeError::UnsupportedField
   - @sffc  should look at this. The variant is still there, but I don't know what the name is supposed to be here
 - Consider making AbstractSerializer not use trait objects for the FsExporter in datagen https://github.com/unicode-org/icu4x/pull/6025
  - This is a stretch issue now.

**Comment by Manishearth** [comment]
I generally consider all of these items to be stretch. We should file issues for ones we care about and close this metaissue.
