### ISSUE TITLE
Stabilize the icu_casemap component

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#3234]
This issue tracks the work to release icu_casemap as a stable component.

Checklist (not exhaustive)

 - [x] Fix data model (https://github.com/unicode-org/icu4x/issues/3481)
 - [x] Code organization (https://github.com/unicode-org/icu4x/pull/3528)
 - [x] Expose case closure methods (https://github.com/unicode-org/icu4x/pull/3544)
 - [x] `full_fold()` functions should work with Writeable (https://github.com/unicode-org/icu4x/pull/3544)
 - [x] Add tests. Ideally upstream conformance tests (https://github.com/unicode-org/icu4x/pull/3553)
 - [x] Add docs (https://github.com/unicode-org/icu4x/pull/3553)
 - [x] Enable boilerplate lints (https://github.com/unicode-org/icu4x/pull/3544)
 - [x] Make `no_std` (https://github.com/unicode-org/icu4x/pull/3544)
 - [x] FFI
   - [x] basic FFI https://github.com/unicode-org/icu4x/pull/3663
   - [x] Add CodePointSetBuilder rather than CPILBuilder over FFI https://github.com/unicode-org/icu4x/pull/3679
   - [x] FFI tests https://github.com/unicode-org/icu4x/pull/3679
 - [x] Move data struct validation into `deserialize` to allow validation-free databake 
 - [x] Review error types, most variants seem to be datagen only
 - [x] Check if we support SpecialCasing.txt (https://github.com/unicode-org/icu4x/pull/3583)
 - [x] Make string APIs more prominent than char APIs (https://github.com/unicode-org/icu4x/pull/3584)
 - [x] Move locale to methods (except for fold/fold_turkic, https://github.com/unicode-org/icu4x/pull/3584)
 - [x] Add `titlecase_segment()` (https://github.com/unicode-org/icu4x/pull/3593)
 - [x] Handle modifiers when performing contextual operations 
 - [x] https://github.com/unicode-org/icu4x/pull/3616
 - [x] Figure out Greek accent uppercasing (https://github.com/unicode-org/icu4x/issues/3552)
 - [x] Also go through [graduation.md](https://github.com/unicode-org/icu4x/edit/main/docs/process/graduation.md) (checklist in https://github.com/unicode-org/icu4x/issues/3234#issuecomment-1636767460)
   - [x]  https://github.com/unicode-org/icu4x/pull/3689
 - [x] Maybe use more UnvalidatedStr in the data model (https://github.com/unicode-org/icu4x/pull/3690)
 - [x] Points from Markus' second review
   - [x]  Decoding should debug_assert on garbage (https://github.com/unicode-org/icu4x/pull/3759)
   - [x] split out separate `TitlecaseMapper<impl AsRef<CaseMapper>>` type, ctors: `new()`, `new_legacy()`, and then the same ones `_with_mapper` https://github.com/unicode-org/icu4x/pull/3779
   - [x] titlecase head adjustment support, with `TitleCaseOptions`, fields `HeadAdjustment { #[default] Adjust, NoAdjust }`, `TailCasing { #[default] Lowercase, PreserveCase }`  https://github.com/unicode-org/icu4x/pull/3779
   - [x] `titlecase_segment_legacy()` on CaseMapper if wanted https://github.com/unicode-org/icu4x/pull/3779
   - [x] `CaseCloser` wrapper for case closure things, similar ctors (https://github.com/unicode-org/icu4x/pull/3759)
 - [x] https://github.com/unicode-org/icu4x/issues/3801

**Comment by Manishearth** [comment]
Added a checklist, please append more items to it

**Comment by Manishearth** [comment]
> [ ] Move data struct validation into `deserialize` to allow validation-free databake

@robertbastian i'm not convinced we should be doing the heavy validation in databake: it's debug-assertions only, and the struct has GIGO behavior if you give it bad data. I think this is the right call, since there's a lot of work in properly validating this data otherwise.

**Comment by robertbastian** [comment]
I don't care, as long as we don't do any validation in databake and I can make the constructor `const`

**Comment by Manishearth** [comment]
There shouldn't be right now, if there is you are welcome to remove it

**Comment by Manishearth** [comment]
Useful note for later: the unfold data currently in use in icu4x

<details>

```rust
[("aʾ", "ẚ"), ("ff", "ﬀ"), ("ffi", "ﬃ"), ("ffl", "ﬄ"), ("fi", "ﬁ"), ("fl", "ﬂ"), ("h\u{331}", "ẖ"), ("i\u{307}", "İ"), ("j\u{30c}", "ǰ"), ("ss", "ßẞ"), ("st", "ﬅﬆ"), ("t\u{308}", "ẗ"), ("w\u{30a}", "ẘ"), ("y\u{30a}", "ẙ"), ("ʼn", "ŉ"), ("άι", "ᾴ"), ("ήι", "ῄ"), ("α\u{342}", "ᾶ"), ("α\u{342}ι", "ᾷ"), ("αι", "ᾳᾼ"), ("η\u{342}", "ῆ"), ("η\u{342}ι", "ῇ"), ("ηι", "ῃῌ"), ("ι\u{308}\u{300}", "ῒ"), ("ι\u{308}\u{301}", "ΐΐ"), ("ι\u{308}\u{342}", "ῗ"), ("ι\u{342}", "ῖ"), ("ρ\u{313}", "ῤ"), ("υ\u{308}\u{300}", "ῢ"), ("υ\u{308}\u{301}", "ΰΰ"), ("υ\u{308}\u{342}", "ῧ"), ("υ\u{313}", "ὐ"), ("υ\u{313}\u{300}", "ὒ"), ("υ\u{313}\u{301}", "ὔ"), ("υ\u{313}\u{342}", "ὖ"), ("υ\u{342}", "ῦ"), ("ω\u{342}", "ῶ"), ("ω\u{342}ι", "ῷ"), ("ωι", "ῳῼ"), ("ώι", "ῴ"), ("եւ", "և"), ("մե", "ﬔ"), ("մի", "ﬕ"), ("մխ", "ﬗ"), ("մն", "ﬓ"), ("վն", "ﬖ"), ("ἀι", "ᾀᾈ"), ("ἁι", "ᾁᾉ"), ("ἂι", "ᾂᾊ"), ("ἃι", "ᾃᾋ"), ("ἄι", "ᾄᾌ"), ("ἅι", "ᾅᾍ"), ("ἆι", "ᾆᾎ"), ("ἇι", "ᾇᾏ"), ("ἠι", "ᾐᾘ"), ("ἡι", "ᾑᾙ"), ("ἢι", "ᾒᾚ"), ("ἣι", "ᾓᾛ"), ("ἤι", "ᾔᾜ"), ("ἥι", "ᾕᾝ"), ("ἦι", "ᾖᾞ"), ("ἧι", "ᾗᾟ"), ("ὠι", "ᾠᾨ"), ("ὡι", "ᾡᾩ"), ("ὢι", "ᾢᾪ"), ("ὣι", "ᾣᾫ"), ("ὤι", "ᾤᾬ"), ("ὥι", "ᾥᾭ"), ("ὦι", "ᾦᾮ"), ("ὧι", "ᾧᾯ"), ("ὰι", "ᾲ"), ("ὴι", "ῂ"), ("ὼι", "ῲ")]
```

</details>

**Comment by Manishearth** [comment]
Should https://github.com/unicode-org/icu4x/issues/3552 be a stabilization blocker? Feels like we can count it as a known bug.

**Comment by Manishearth** [comment]
Also, ICU4C supports [`str.toTitle(locale, options)`](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/classicu_1_1UnicodeString.html#a2c3114c21af4433a2a1a7f22950382b8). Should we as well? Currently we do not support `options`, we can add them as an API later (`to_upper_with_options()` or something)

**Comment by Manishearth** [comment]
The `toTitle()` functions need a break iterator: we need to add APIs which:

 - Instantiate a default word break iterator
 - Allow passing in a word break iterator 

I also think this can be designed in a later release.

**Comment by Manishearth** [comment]
question (@sffc , @robertbastian ): Do the current function names look good to you?

 - `to_uppercase(char) -> char`
 - `to_full_uppercase(&str) -> Writeable`
 - `to_full_uppercase_string(&str) -> String`

I somewhat feel like the stringy one should be the one with the shorter name, and the char one should be `to_uppercase_char()`

**Comment by Manishearth** [comment]
A change we should make is move the locale from the constructor to the methods. We can make them all take `CaseMappingLocale` and have people call `.into()` or `Default::default()`. We could also give them `_with_locale()` versions but that might lead to a large proliferation.


Thoughts?

**Comment by eggrobin** [comment]
> Do the current function names look good to you?
>
> to_uppercase(char) -> char
> to_full_uppercase(&str) -> Writeable
> to_full_uppercase_string(&str) -> String
> I somewhat feel like the stringy one should be the one with the shorter name, and the char one should be to_uppercase_char()

The simple mappings and foldings (which you should practically never use unless you have specific compatibility requirements) having shorter and more default-looking names than the default ones seems like a bad idea. I would favour renaming all of the char-to-char functions to have `simple` in the name, this is a well-established term in this context.

> A change we should make is move the locale from the constructor to the methods.

Something like that would be a good idea. It is very weird that the case foldings _look like_ they depend on the locale, which they do not and must not.

**Comment by robertbastian** [comment]
We might actually want to accept `W: Writeable` like list formatting does already.

**Comment by Manishearth** [comment]
> What is your idea for `CaseMappingLocale` and how does it differ from Locale or DataLocale? Keep in mind that we're still pending the rearchitecting of ICU4X's Locale/Preferences handling so I might not want to deviate too far from the existing types given that they might change again in the near future.

It's what's already used internally, it's a simple enum:

```rust
pub enum CaseMapLocale {
    Root,
    Turkish,
    Lithuanian,
    Greek,
    Dutch,
    Armenian,
}
```

and it basically covers the different casemapping special-case modes. ICU4C's API consumes a Locale; but it does feel potentially faster to not require a conversion each time, and exposing something that is `From<Locale>` seems fine.

This way we only require the actual subpart of the locale the algorithm cares about, instead of having clients treat it opaquely.

**Comment by Manishearth** [comment]
Copying over Markus' feedback from the ICU4X team meeting notes


> * What's the difference between try_new and try_new_with_locale?
> * Give examples for all the functions, especially to_titlecase(char)->char (dz -> Dz)
> * Do we support specialcasing.txt?
> * There are some things that are only in ICU and not in data. Example: Greek uppercasing, which drops most but not all accents, but with certain exceptions. It's not representable in data, so it is coded manually.
> * Long term we want the Edits API. Clients need it like Chrome.
> * People will want full titlecase, but it requires segmentation. Maybe make it pluggable with a trait. A default implementation could be to titlecase only the first character. When titlecasing, sometimes you want to leave interior characters along, and sometimes you want to convert them to lowercase.
> * Take a look at the ICU4J CaseMap API!
> * In ICU, the locale-special data are stored in the same trie as root data, so we can specify the locale later.
> * For case folding, the locale doesn't matter, only turkic and non-turkic. Right now it's confusing because it looks like the locale could influence case folding.


I do think I'm going to go along the path of doing titlecase with a segmentation trait.

**Comment by Manishearth** [comment]
I've copied the actionable bits of Markus' feedback, as well as stuff discussed here, into the issue above.

I'm not sure if it's either-or: full-string titlecase isn't that tricky, whereas Greek uppercase seems to involve reimplementing half of the uppercasing algorithm, without any spec for reference.

**Comment by Manishearth** [comment]
Discussions to have:

 - General API shape (Rust and FFI) for locale specific stuff
 - Greek uppercasing thing
 - Titlecasing design

**Comment by sffc** [comment]
Discuss with:

- @sffc 
- @robertbastian 
- @eggrobin 
- @Manishearth

**Comment by Manishearth** [comment]
Discussion:

CaseMapLocale:
 
 - @robertbastian Probably should take a locale on the methods (as opposed to a custom enum)
 - @sffc Agree, I consider it a language hint
 - @eggrobin Note that folding should not be treated as locale-dependent, "turkic casefolding" should be considered to be a different operation
 - @eggrobin pointing out that the spec has four casefolding operations: toCaseFold, NFD ∘ toCaseFold ∘ NFD, NFKD ∘ toCaseFold ∘ NFD, toNFKC_Casefold ∘ NFD 
 - Should we accept Language or Locale
 - @Manishearth: note that in the future someone may decide they want `de-u-cm-ß`
 - If we do an enum (or opaque struct wrapping an enum) it shuld be called `CaseMapLanguageHint`
 - Decision: LanguageIdentifier, Locale over FFI
 - Decision: No `to_uppercase_root()`

Titlecasing:
 - Don't expose full segmentation based API. Expose `titlecase_segment(&str, &langid) -> String / Writeable` that does not handle any segmentation
 - Add more if someone asks for it

Simple case mapping:
  - Methods called `to_simple_lowercase(char) -> char`. 

Greek uppercasing:
 - @sffc Should not treat ICU4C parity as a goal
 - @Manishearth and @eggrobin: "i18n correct" is not feasible without tons of research
 - @sffc iff this is going to be coming to CLDR/some other body, we should wait for it. If not, we should block our release.
 - @Manishearth and @robertbastian do not disagree
  - @eggrobin We could take the position that we do best-effort ICU4C parity
- Decision: Defer until [PAG meeting](https://github.com/unicode-org/properties/issues/138), based on response decide to block release or not. Potentially implement anyway.
 

Agreed: @Manishearth @sffc @robertbastian @eggrobin

**Comment by Manishearth** [comment]
Graduation checklist

- [ ] The crate should fully conform with the [ICU4X Style Guide](style_guide.md):
  - [ ] The crate should have a complete library header as shown in [boilerplate.md](boilerplate.md) with Clippy passing
  - [ ] The names of exported types should conform to the recommendations in the Style Guide
  - [ ] All Error types should be `Copy`
  - [ ] All constructors should take options structs by value
  - [ ] All constructors should take arguments in the following order: Provider, Locale, Options
  - [ ] All constructors should have the standard set of overloads for provider types
  - [ ] Runtime dependencies should be minimal and able to be disabled with Cargo features if possible
- [ ] The crate should have a conventional Cargo.toml file:
  - [ ] Cargo.toml should use license, not license-file
  - [ ] The description should be useful
  - [ ] Correct repo link, authors, categories, include
  - [ ] Correct docs.rs and cargo-all-features metadata settings
  - [ ] A `rust-version` field with the MSRV of this crate in accordance with the current ICU4X policies on MSRV.
  - [ ] The crate should have an `std` feature if (and only if) it contains code that depends on `std`, such as file I/O or implementing the Error trait
  - [ ] Audit all features so that any `foo/bar` in a feature is `foo?/bar` when `foo` is an optional dep; if you intend to enable `foo`, add two entries
  - [ ] Use `dep:` for enabling dependencies
- [ ] The crate should be fully documented
  - [ ] Every exported function should have docs coverage
  - [ ] There should be a crate-level example that illustrates a common use case for the component
  - [ ] All options and conditional code paths should have a corresponding docs test
- [ ] The data structs should fully follow ZeroVec style
  - [ ] Deserialization should not have a "net violation" in the [verify-zero-copy](https://github.com/unicode-org/icu4x/blob/main/provider/datagen/tests/verify-zero-copy.rs) test
  - [ ] Constructors should avoid allocating memory in the common case
  - [ ] Opaque blobs of data should be avoided if possible (instead use VarZeroVec, ZeroMap, etc.)
  - [ ] Data structs should not be panicky to load/deserialize and conform to [data_safety.md](https://github.com/unicode-org/icu4x/blob/main/docs/design/data_safety.md)
- [ ] The component should be fully integrated with ICU4X tooling
  - [ ] There should be an overview Criterion benchmark
  - [ ] There should be individual Criterion benchmarks for interesting or performance critical code paths
  - [ ] There should be at least one example plumbed with the icu_benchmark_macros
  - [ ] The component should be fully covered by FFI with no unjustified suppressions nor entries in missing_apis.txt
- [ ] The component should encourage i18n best practices
  - [ ] The component should produce correct results in all locales as generated by icu4x-datagen
  - [ ] Where applicable, the component should be consistent with ECMA-402 and UTS #35
  - [ ] Any gaps in i18n quality should be fixed, or, if that is not possible, they should have tracking issues and a concrete, resourced path forward. The intent is to not ship components with known i18n correctness problems and no plan to fix them in an upcoming release
  - [ ] The API design should receive sign-off from a non-ICU4X i18n expert such as Markus Scherer

**Comment by Manishearth** [comment]
(I'm opening a PR to polish up some of the boxes I've prematurely ticked in the checklist above)

@sffc   I think there are a couple entries in the checklist that may benefit from a 15 minute pair discussion where we verify it together. Specifically: the style guide naming part, i18n correctness, and data struct design

**Comment by Manishearth** [comment]
- [ ] debug_assert in Exceptions datagen when doing GIGO

**Comment by sffc** [comment]
I added the new checkboxes from #3693 to the comment above.

A few things I notice:

- You have `# Example` instead of `# Examples` (I know, minor silly thing that I don't necessarily agree with, but this is the time to fix it)
- I don't see examples for [TailCasing](https://unicode-org.github.io/icu4x/docs/icu_casemap/titlecase/enum.TailCasing.html) or [HeadAdjustment](https://unicode-org.github.io/icu4x/docs/icu_casemap/titlecase/enum.HeadAdjustment.html); it looks like you cover them in the docs for `TitlecaseMapper` itself, which is fine, but please add a link.
- This check box is not checked yet: "There should be at least one example plumbed with the icu_benchmark_macros"

**Comment by Manishearth** [comment]
> This check box is not checked yet: "There should be at least one example plumbed with the icu_benchmark_macros"

Yeah I was planning to do that later. But I'll just roll it into #3803

**Comment by Manishearth** [comment]
I think I have handled every box on this page except for  https://github.com/unicode-org/icu4x/issues/3801 in https://github.com/unicode-org/icu4x/pull/3803

(even if not, I would prefer to land that rather than require that PR fix everything)

**Comment by Manishearth** [comment]
Final checkbox checked by https://github.com/unicode-org/icu4x/pull/3843

We're done!
