### ISSUE TITLE
ICU4X 1.2 release checklist

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#3297]
# Extra pre-checklist checklist

 - [x] Update Diplomat (https://github.com/rust-diplomat/diplomat/pull/323, https://github.com/unicode-org/icu4x/pull/3304)
 - [x] (@Manishearth) Write a changelog (draft: https://hackmd.io/@Manishearth/BkIpZnSGh/edit)
 - [x] Utils bumps https://github.com/unicode-org/icu4x/pull/3308

# Main checklist

* [x] (@manishearth) Run `cargo +nightly fmt -- --config=format_code_in_doc_comments=true --config=doc_comment_code_block_width=80` to prettify our docs (https://github.com/unicode-org/icu4x/pull/3309)
* [x] (@sffc) Run `cargo update` for each `Cargo.lock` file to update our CI to freshest dependencies
* [x] (@sffc) Verify that the milestone and checklist are complete
* [x] Verify with component owners that they're ready for release
* [x] (@Manishearth) Verify that `ffi/diplomat` depends on a released (not Git) version of Diplomat. Get it published (ask manishearth or sffc) otherwise.
* [x] Verify that we have acceptable FFI coverage (should be a part of the checklist issue)
  * [x] Verify that `ffi/diplomat/tests/missing_apis.txt` is empty. If not, check with the team that we are okay punting these to the next release.
  * NOTE: We can ship 1.2 with a known issue that not all APIs are covered.
* [x] Take a bird-eye view at:
  * [x] (@sffc) READMEs
  * [x] (@echeran) Documentation
  * [x] (@Manishearth) Coverage
  * [x] (done in meeting) Performance / Memory / Size benchmarks
  * [x] (@sffc) Cargo.toml files
    * [x] Cargo.toml files need to specify versions for each entry in `dependencies`.
    * [x] Cargo.toml should not specify versions for each entry in `dev-dependencies`.
    * [x] Ensure that any new packages have suitable version numbers.
    * [x] Ensure that the Cargo.toml file includes a set of fields consistent with other ICU4X packages.
* [x] (@sffc) `cargo workspaces version --no-git-push` to bump the version numbers
  * [x] This will only update crates that have changed, and will ask you which version number to bump for each crate
  * [x] You can use commands like `git log icu@1.0.0..@ -- components/plurals/src/` and `cargo public-api -p icu_list diff 1.0.0` to figure out whether to do a major, minor, or patch release
  * [x] Get this reviewed and checked in before continuing
* [x] (@Manishearth) Use `cargo workspaces publish --from-git` to automatically publish the crates in the correct order
  * [x] Add `icu4x-release` group as owners to each new component you're publishing
    * [x] `cargo owner -a github:unicode-org:icu4x-release`
* [x] (@sffcManishearth Verify that the tutorial crates work on the newly released crates.io sources by running `cargo make test-cargo-tutorial-cratesio`
  * [x] If there are any errors, please fix them before advertising the release
* [x] (@Manishearth) [Tag the Release](https://github.com/unicode-org/icu4x/releases)

# To do in the coming days

* [x] Announce the release to public
  * [x] Send an email to [icu4x-announce](https://groups.google.com/u/0/a/unicode.org/g/icu4x-announce)

**Comment by Manishearth** [comment]
Changelog is done. @sffc please note that in the experimental section I have marked a bunch of crates as "no other changes", the only changes are edition bumps and clippy fixes. If you want you can publish new versions for them, in which case please note down the version diff since 1.1, otherwise please  have it say "No change (still at x.y.z)", the same way we do for the utils.

The idea is that since we only write changelogs for ICU4X releases, we should cover all intermediate versions.

**Comment by Manishearth** [comment]
note to self: workspaces tool should have `--no-git-tag`

**Comment by Manishearth** [comment]
Release is published and tagged. Heading for lunch

**Comment by sffc** [comment]
For line break, ICU4X 1.2 contains these data entries:

```
segmenter/lstm/wl_auto@1/my.postcard
segmenter/lstm/wl_auto@1/km.postcard
segmenter/lstm/wl_auto@1/lo.postcard
segmenter/lstm/wl_auto@1/th.postcard
segmenter/grapheme@1/und.postcard
segmenter/line@1/und.postcard
```

gzipped together, these are 299959 B.

The equivalent in ICU4C 72 should be:

```
brkitr/burmesedict.dict
brkitr/char.brk
brkitr/khmerdict.dict
brkitr/laodict.dict
brkitr/line.brk
brkitr/line_cj.brk
brkitr/line_loose.brk
brkitr/line_loose_cj.brk
brkitr/line_loose_phrase_cj.brk
brkitr/line_normal.brk
brkitr/line_normal_cj.brk
brkitr/line_normal_phrase_cj.brk
brkitr/line_phrase_cj.brk
brkitr/thaidict.dict
```

gzipped together, those files are 762631 B.

**Comment by sffc** [comment]
Comparing for the other three segmenter types:

Grapheme:

```
ICU4C:
charbrk/char.brk

ICU4X:
charbrk/grapheme@1/und.postcard
```

Sentence:

```
ICU4C:
sentbrk/sent.brk

ICU4X:
sentbrk/sentence@1/und.postcard
```

Word:

```
ICU4C:
wordbrk/burmesedict.dict
wordbrk/char.brk
wordbrk/laodict.dict
wordbrk/word.brk
wordbrk/thaidict.dict
wordbrk/khmerdict.dict
wordbrk/cjdict.dict

ICU4X:
wordbrk/word@1/und.postcard
wordbrk/w_auto@1/ja.postcard
wordbrk/grapheme@1/und.postcard
wordbrk/wl_auto@1/my.postcard
wordbrk/wl_auto@1/km.postcard
wordbrk/wl_auto@1/lo.postcard
wordbrk/wl_auto@1/th.postcard
```

Gzip Sizes:

| Type | ICU4C | ICU4X |
|---|---|---|
| Char | 2889 | 2438 |
| Sentence | 4352 | 4295 |
| Word | 2286466 | 1852208 |
