### ISSUE TITLE
Checklist for Transliteration

### ISSUE THREAD

**Issue by skius** [unicode-org/icu4x#3736]
Opening this issue to keep track of outstanding issues/features to land experimental transliteration. Things marked as (2) can be done after an initial (end-to-end) version has landed.

- [x] Prework
   - [x] Modern UnicodeSet support - (#3670)
   - [x] Figure out ICU transliteration behavior 
- [x] Data
   ~- [ ] Add data source for transform rules (@robertbastian)
       - [ ] After that, adjust the compiled_data `config.json`.
       - [ ] After that, remove workaround in `download-repo-sources.rs`~
   ~- [ ] (2) Once we know more about the properties used in CLDR data, update #3559~
- [x] Datagen
   - [x] Design the data struct - #3627
      - [x] Rethink cursor serialization - could also be a hardcoded and reserved single code point for cursors without placeholders off either end of the text (e.g., `<CURSOR>`), and could be `<CURSOR><offset as char>` for cursors with an offset/placeholders off either end of the text. Likely always need the `<offset as char>` data for easier deserialization, so for an inline cursor we would have `<CURSOR>\0` - #3937
      - [x] Change segments representation - #3943
      ~- [ ] Polish data struct - #3850~
      ~- [ ] (2) Inlining UnicodeSets derived from properties can lead to duplication of data across transliterators (e.g., two transliterators that both use `[:Lowercase:]` would have a lot of duplicate data). Maybe think about some constant-sized serialization special case for properties, e.g., just serializing "property: Lowercase", and then loading that property with the property's datamarker, meaning only some ID for `Lowercase` is duplicated across transliterators, not the actual property data, which lives with the usual property provider.~
   - [x] Parse source files for rules - #3730
      ~- [ ] (2) Test parse error messages~
         ~- [ ] (2) Remove associated `#[allow(unused)]`~ 
      - [x] (2) Handle (ignore) ICU transform rule pragmas, e.g., `use variable range ...` - #3995
   - [x] Compile parsed sources into datastructs - #3824, #3822
      - [x] Validate rule items are well-formed per direction  - #3819 
      - [x] Decide handling of bidirectional sources - #3646
      - [x] Remove associated TODOs in `parse.rs` - #3827
      - [x] Return list of dependency locales (strings) - #3877
      - [x] Check that PUA range suffices for all specials (including backrefs and anchors) - #3824
      - [x] Check for backref encoding overflows - #3827
      - [x] Add compilation for cursors - #3937
      - [x] Add compilation for recursive transliterators (`SingleId`) by passing/creating the (datagen-global) mapping from legacy ID to internal ID - #3877
      ~- [ ] (2) Errors with source location (adding a `usize` to `parse::*` types, whether directly or with a generic "SpanWrapper", is probably the easiest way)~
         ~- [ ] (2) Similarly, logging with source location/source text?~
      ~- [ ] (2) Decide what (non-critical) validation checks should be performed. Questions include:~
         ~- Enforce no special replacers (backreferences, function calls, cursors) in (implicitly ignored) target contexts?~
         ~- Enforce empty target contexts for unidirectional rules?~
         ~- Enforce no anchors on target-side and no cursors on source-side for unidirectional rules?~
      ~- [ ] (2) Decide if validation should be done for both directions even if source file defines only one direction~
         ~- [ ] (2) Similarly, decide if non-source-file-defined directions are even allowed (is `a < b` a valid rule in a `forward` transliterator?)~
   - [x] Add the right crate features to `transliteration` and `transliterator_parser`.
      - [x] `transliteration` - #3877
      - [x] `transliterator_parser`
   - [x] Add `bakeddata` support to `transliteration` - #3877
   ~- [ ] (2) Unify parse+compile tests (currently difficult to judge where an edge case is tested)~
   - [x] Datagen glue code - #3877
      - [x] Parse provided metadata sources (ID, visibility, ...) and pass to compilation
      - [x] Provide direction (part of metadata) to parsing/compilation, and act accordingly
         - [x] Parse: log warnings (or even error?) when a rule uses an unspecified direction (e.g. `b < a` with `forward` metadata)
         - [x] Compile: compile datastructs only for the directions the metadata specifies
   ~- [ ] (2) Build and use dependency graph for transliterators for datagen~
      - [x] Skippable in the initial version by generating data for everything
      ~- [ ] (2) Generate data for transitive dependencies when specifying a certain locale~
      ~- [ ] (2) Handle (potentially) special-cased datagen for builtin transliterators (Upper, Title, Lower, ...)~
         ~- [ ] (2) Some builtin transliterators might also not require any data, like Any-Remove~
- [x] Locales
   - [x] Design internal representation of transliterator IDs (`source/target`) - #3765
      - [x] Parsing in DataLocale (add `aux: String` and update `strict_cmp`, ...)
      - [x] Hardcode the reverse of special transliterators (see [these](https://unicode-org.github.io/icu/userguide/transforms/general/#custom-inverses)) - #3994
      - [x] Representation of custom transliterators - #3891
   ~- [ ] (2) Parsing for legacy UTS#35 IDs (e.g., `und_Source-und_Target`)~
      - [x] Skippable in the initial version by matching on metadata purely during datagen (keep track of `legacy ID => transliterator` map during datagen/parsing - #3877
- [x] Runtime
   - [x] Implement data struct - #3775
      - [x] (2) Detailed documentation of the format - #3776
   ~- [ ] Open issue detailing discussed API~
      ~- [ ] Separate fallback chain for single locales for transliteration~
      ~- [ ] Lockstep transliterator fallback mechanism (UTS#35) in Transliterator constructor~
         ~- [ ] Answer: How to do fallback on composite special+regular source/target locales? - #3950~
      ~- [ ] Can users override internal transliterators? - #3911~
   ~- [ ] Add hardcoded ICU transliterators (e.g., Any-Hex, see special classes that exist in ICU4J) - #3910~
      ~- [ ] Handle BCP-47 for them at runtime + datagen time - #3909~
   - [x] Use (copy-pasted, offline preprocessed) [CLDR testData](https://github.com/unicode-org/cldr/tree/main/common/testData) for integration tests. 
      ~- [ ] Once we have this, how do we keep this up to date?~
   ~- [ ] Steal [ICU4C tests](https://github.com/unicode-org/icu/blob/main/icu4c/source/test/intltest/usettest.cpp)~
- [x] Polish
   ~- [ ] Add detailed comments to parser~
   ~- [ ] Factor out escape parsing together with `unicodeset_parser`'s escape handling somehow~
   ~- [ ] Data-gen optimizations - #3825~
   ~- [ ] DatagenProvider impl only compute transliterator map once instead of per `load`~
   ~- [ ] Pretty-print intermediate structs back to source syntax (would allow for round-trip testing)~
   ~- [ ] Apply parse error conclusions from #3558~
   - [x] Add a `&'static str` to `PEK::Internal` for better bug error messages - #3996
   ~- [ ] Test all data structs built from our data to be "valid" in the sense that the VarTable layout is applicable to the encoded rules~
   ~- [ ] Add benchmarking for transliteration and resolve optimization comments in codebase - #3957~
   ~- [ ] Cleanup - #3958~

**Comment by skius** [comment]
Initial transliteration support has landed. See here for the road to stabilization: https://github.com/unicode-org/icu4x/issues/3961
