### ISSUE TITLE
Graduation checklist for new calendars

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#4053]
- [x] The crate should fully conform with the [ICU4X Style Guide](https://github.com/unicode-org/icu4x/blob/main/docs/process/style_guide.md):
  - [x] The crate should have a complete library header as shown in [boilerplate.md](https://github.com/unicode-org/icu4x/blob/main/docs/process/boilerplate.md) with Clippy passing
  - [x] The names of exported types should conform to the recommendations in the Style Guide
  - [x] All Error types should be `Copy`
  - [x] All constructors should take options structs by value
  - [x] All constructors should take arguments in the following order: Provider, Locale, Options
  - [x] All constructors should have the standard set of overloads for provider types
  - [x] Runtime dependencies should be minimal and able to be disabled with Cargo features if possible
  - [x] Any `TODO`, `FIXME`, `todo!`, `unimplemented!`, or other placeholders should either be resolved or link to an issue number. (It is okay to ship a small amount of code with tech debt comments, but anything having to do with code correctness should be resolved)
- [x] The crate should have a conventional Cargo.toml file:
  - [x] Cargo.toml should use license, not license-file
  - [x] The description should be useful
  - [x] Correct repo link, authors, categories, include
  - [x] Correct docs.rs and cargo-all-features metadata settings
  - [x] A `rust-version` field with the MSRV of this crate in accordance with the current ICU4X policies on MSRV.
  - [x] The crate should have an `std` feature if (and only if) it contains code that depends on `std`, such as file I/O or implementing the Error trait
  - [x] Audit all features so that any `foo/bar` in a feature is `foo?/bar` when `foo` is an optional dep; if you intend to enable `foo`, add two entries
  - [x] Use `dep:` for enabling dependencies
- [x] The crate should be fully documented
  - [x] Every exported function should have docs coverage
  - [x] There should be a crate-level example that illustrates a common use case for the component with the heading `# Examples`
  - [x] All options and conditional code paths should have a corresponding docs test with the heading `# Examples`
  - [x] All functions that are conditional on a Cargo feature should say so (last line before `# Examples`): ```✨ *Enabled with the `alloc` Cargo feature.*```
  - [x] Compiled data constructors should say "with compiled data" in the first sentence and should have a Cargo feature alert following the above syntax.
- [x] The data structs should fully follow ZeroVec style
  - [x] Deserialization should not have a "zero-copy violation" in the [make-testdata](https://github.com/unicode-org/icu4x/blob/main/provider/datagen/tests/make-testdata.rs) test
  - [x] Constructors should avoid allocating memory in the common case
  - [x] Opaque blobs of data should be avoided if possible (instead use VarZeroVec, ZeroMap, etc.)
  - [x] Data structs should not be panicky to load/deserialize and conform to [data_safety.md](https://github.com/unicode-org/icu4x/blob/main/docs/design/data_safety.md)
- [ ] The component should be fully integrated with ICU4X tooling
  - [x] There should be an overview Criterion benchmark
  - [x] There should be individual Criterion benchmarks for interesting or performance critical code paths
  - [ ] There should be at least one example plumbed with the icu_benchmark_macros
  - [x] The component should be fully covered by FFI with no unjustified suppressions nor entries in missing_apis.txt
- [ ] The component should encourage i18n best practices
  - [x] The component should produce correct results in all locales as generated by icu4x-datagen
  - [x] Where applicable, the component should be consistent with ECMA-402 and UTS#35
  - [x] Any gaps in i18n quality should be fixed, or, if that is not possible, they should have tracking issues and a concrete, resourced path forward. The intent is to not ship components with known i18n correctness problems and no plan to fix them in an upcoming release
  - [ ] The API design should receive sign-off from a non-ICU4X i18n expert such as Markus Scherer

**Comment by robertbastian** [comment]
I believe the plan for the new calendars is to launch the stable API in 1.3, so we should tick all the API-facing boxes of the checklist. Imho this should include FFI, which is [missing](https://github.com/unicode-org/icu4x/blob/main/ffi/diplomat/tests/missing_apis.txt#L17-L54) at the moment.

**Comment by Manishearth** [comment]
> Since we like optional dependencies, should we make calendrical_calculations an optional feature that enables all the calendars that need it?

This is all calendars. There is no point.

> The four islamic calendars and Hebrew have pub fn new(); is this intended 

No, I suspect the interns added it in response to clippy lints

> We should add tests for this somehow.

I'm pretty sure they are added to AnyCalendar already and tested. The comments are outdated 

> There is not consistent bench coverage for the calendars

Yeah I consider this a problem for when we're actually optimizing these.

**Comment by Manishearth** [comment]
> I'm pretty sure they are added to AnyCalendar already and tested. I modified a test the other day that had these listed. The comments are outdated



Ah, this method isn't quite tested, but I also can't think of a way to test it that would actually trigger when you add a new calendar and don't add this method. Not implementing it will cause missing formatting though.

**Comment by sffc** [comment]
I bet the tests were passing because the function that uses this value reads

```
    fn convert_if_necessary<'a>(
        &'a self,
        value: &impl DateInput<Calendar = AnyCalendar>,
    ) -> Result<Option<Date<icu_calendar::Ref<'a, AnyCalendar>>>, DateTimeError> {
        let this_calendar = self.1.kind();
        let date_calendar = value.any_calendar_kind();

        if Some(this_calendar) != date_calendar {
            if date_calendar != Some(AnyCalendarKind::Iso) {
                return Err(DateTimeError::MismatchedAnyCalendar(
                    this_calendar,
                    date_calendar,
                ));
            }
            let date = value.to_iso().to_any();
            let converted = self.1.convert_any_date(&date);
            Ok(Some(converted))
        } else {
            Ok(None)
        }
    }
```

so if the any_calendar_kind is `None`, the date just gets converted via `.to_iso().to_any()`.

**Comment by sffc** [comment]
I think we could test in the fixture tests that if you pass the AnyDate into an AnyDateTimeFormatter with the wrong calendar, then it should return an error.

**Comment by Manishearth** [comment]
Do you want to try prototyping that?

**Comment by Manishearth** [comment]
I ended up doing it

**Comment by sffc** [comment]
I think this is DONE now.

**Comment by robertbastian** [comment]
> > Since we like optional dependencies, should we make calendrical_calculations an optional feature that enables all the calendars that need it?

> This is all calendars. There is no point.

Some calendars require libm and float calculations though, and some don't. I can imagine this is a dependency that clients might want to shed, but we can do this later.

**Comment by sffc** [comment]
The place ECMAScript Temporal draws the line is that the ISO calendar is built in and all others (including Gregorian, which differs from ISO in that it has month and era codes) are an extension.
