### ISSUE TITLE
1.4 release checklist

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#4300]
* [x] Verify that the milestone and checklist are complete
* [x] Verify with component owners that they're ready for release
* [x] Take a bird-eye view at:
  * [x] READMEs
  * [x] Documentation
  * [ ] Coverage
  * [ ] Performance / Memory / Size benchmarks
  * [x] Cargo.toml files
    * [x] All dependencies from the workspace should use `workspace = true` rather than their version number or path 
    * [x] Cargo.toml files need to specify versions for each non-workspace entry in `dependencies`, or use `workspace = true`.
    * [x] Ensure that any new packages have version number `0.0.0`, this will making bumping during the release easier.
    * [x] Ensure that the Cargo.toml file includes a set of fields consistent with other ICU4X packages.
        * These should mostly use workspace inheritance
* [x] Run `cargo +nightly fmt -- --config=format_code_in_doc_comments=true --config=doc_comment_code_block_width=80` to prettify our docs
* [x] Verify that `ffi/capi` depends on a released (not Git) version of Diplomat. Get it published (ask manishearth or sffc) otherwise.
* ~[ ] Run `cargo update` for each `Cargo.lock` file to update our CI to freshest dependencies~
  * Given up because too many dependencies don't support 1.67 anymore, and there's no automated way to get the last release that supports 1.67
* [x] Go through `ffi/capi/tests/missing_apis.txt` and verify that it is empty. If it is not, component owners should either add FFI APIs, add `rust_link` annotations, or allowlist the relevant APIs as having been punted to the future
* [x] Start work on a changelog (see below)
* [x] Draft the text for the GitHub release. This text will be sent to GitHub subscribers and can also be used for the mailing list email.
* [x] Prepare a PR to update tutorials using the upcoming release. The PR should pass `cargo make test-tutorials-local`, but can fail `cargo make test-tutorials-cratesio` prior to release

**Comment by younies** [comment]
What is the deadline for this release ?

**Comment by robertbastian** [comment]
Draft release text:

This release contains datagen support for CLDR 44 and ICU 74, with compiled data also updated to these versions. Additionally, there's an improved smaller data model for the blob provider, as well as smaller bug fixes.

**Comment by sffc** [comment]
> What is the deadline for this release ?

Yes, sorry I realized that if you didn't tune into the ICU4X Summit you might not have been in the loop. I just sent out an email with the notes and key takeaways from the summit.

> Draft release text:

How about:

This release includes CLDR 44 and Unicode 15.1 compiled data and datagen support. It also includes a smaller blob provider format, experimental support for plural ranges and rounding increment, and several smaller bug fixes.
