### ISSUE TITLE
Implement and optimize ZeroVec

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#652]
To-do items:

- [ ] Make work with TinyStr (https://github.com/zbraniecki/tinystr/pull/44)
- [ ] Integrate with pattern utils (follow-up: #519)
- [x] ~Pull out the borrowed version so it doesn't have to be an enum?~ Punted to backlog: #676
- [x] Add a map version (Manish)
- [ ] Migrate the ICU4X data structs to use ZeroVec (follow-up: #856)
- [x] Add to style guide (#699)
- [ ] Benches for ZeroMap (follow-up: #853)

**Comment by sffc** [comment]
I'm marking this issue as completed.  I opened follow-up issues for the remaining action items.
