### ISSUE TITLE
Implement ListFormat

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#800]
ECMA-402 includes [ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat), a formatter that supports localized formatting of lists of things.

ListFormat is specified in both ECMA-402 and [UTS-35](https://unicode.org/reports/tr35/tr35-general.html#ListPatterns).  ECMA-402 should serve as a basis for the API design, and UTS-35 for the implementation.

When implementing this in ICU4X, keep the following in mind:

- As much as possible, leverage utilities such as pattern utils and FormattedStringBuilder. Avoid reinventing the wheel.
- Implement and thoroughly test the language-specific overrides such as the ones used for Spanish and Hebrew noted in UTS 35.
- We should try to bubble up nested fields from child formatters.  For example, if formatting a list of units, we should bubble up the fields from the unit formatter.

Steps to get started:

- [ ] Read the CLDR spec for ListFormat
- [ ] Implement the CLDR transformer
- [ ] Implement ListFormat on top of FormattedStringBuilder

**Comment by zbraniecki** [comment]
I consider `ListFormat` to be one of the foundational components (in contrast to "leaf" components like RelativeTimeFormat) - I think in ECMA-402 we so far underestimated how many items can and should be composited into some forms of lists.
`5 hours, 39 minutes` is a list, `6'1"` is a list, `10 km and a half` is a list.

For that reason, I believe we need to further scope out the MVP for LIstFormat that can be self-contained, provide basic support for ECMA-402 compatibility, *and* lay the groundwork for further composition with other formatters.

**Comment by sffc** [comment]
2021-06-24:

- This is blocked on #135, which allows us to compose formatters.
- Implement `SimpleListFormat` based on ECMA-402 and UTS 35, leaving the name `ListFormat` open for an all-in-one formatter in the future that does what @zbraniecki described above.

**Comment by sffc** [comment]
@robertbastian Is this issue complete?
