### ISSUE TITLE
Tracking Issue: TimeZones 1.0

### ISSUE THREAD

**Issue by nordzilla** [unicode-org/icu4x#887]
# TimeZones 1.0

This is a tracking issue for everything that is left to do in order to consider time zones feature-complete in ICU4X.

I have currently added a list of every bit of functionality (that I am aware of) that we still need to support before a 1.0 release.

I will be filing specific issues for all of the items marked `#TBD`.

If any new issues come up, I will be adding them to the list and tracking them here.

## Useful Links
- **UTS-35**
    - [[Date and Date Ranges](https://www.unicode.org/reports/tr35/tr35-39/tr35.html#Date_Ranges)]
    - [[Date Format Patterns](https://www.unicode.org/reports/tr35/tr35-39/tr35-dates.html#Date_Format_Patterns)]
    - [[Time Zone Identifiers]](https://www.unicode.org/reports/tr35/tr35-39/tr35.html#Time_Zone_Identifiers)
    - [[Time Zone Names](http://www.unicode.org/reports/tr35/tr35-39/tr35-dates.html#Time_Zone_Names)]
    - [[Using Time Zone Names](https://www.unicode.org/reports/tr35/tr35-39/tr35-dates.html#Using_Time_Zone_Names)]
- **CLDR**
    - [[metaZones.json : metazoneInfo](https://github.com/unicode-org/cldr-json/blob/39205fdc027c935e52a268afcf01cd240f3c442d/cldr-json/cldr-core/supplemental/metaZones.json#L8)] 
    - [[windowsZones.json : mapTimezones](https://github.com/unicode-org/cldr-json/blob/39205fdc027c935e52a268afcf01cd240f3c442d/cldr-json/cldr-core/supplemental/windowsZones.json#L8)] 
    - [[primaryZones.json : primaryZones](https://github.com/unicode-org/cldr-json/blob/39205fdc027c935e52a268afcf01cd240f3c442d/cldr-json/cldr-core/supplemental/primaryZones.json#L7)]
- **TZDB**
    - [[Olson/IANA Time Zone Database](https://www.iana.org/TimeZones)]

## Criteria

- [ ] TimeZoneFormat V1.0
    - [ ] UTS-35 Patterns
        - [ ] LowerZ
            - [ ] #TBD Handle Type Fallback for non-location formats.
            - [ ] #TBD Handle Fallback Format for non-location formats.
        - [ ] UpperO
            - [ ] #TBD Use NumberFormat in Localized GMT Format.
        - [ ] UpperV
            - [ ] Length(1)
                - [ ] #TBD Implement short TimeZone name for TimeZoneFormat
            - [ ] Length(2)
                - [ ] #TBD Implement long TimeZone name for TimeZoneFormat
            - [ ] Length(4)
                - [ ] #TBD Use regionFormat in Generic Location Format
        - [ ] LowerV
            - [ ] Length(1)
                - [ ] #TBD Handle Type Fallback for non-location formats.
                - [ ] #TBD Handle Fallback Format for non-location formats.
            - [ ] Length(2)
                - [ ] #TBD Handle Type Fallback for non-location formats.
                - [ ] #TBD Handle Fallback Format for non-location formats.
    - [ ] DataProvider
        - [ ] #TBD Store canonicalized TZID in TimeZone data
        - [ ] #TBD Retrieve localized metazone info from timeZoneNames.json
        - [ ] #TBD Determine how we will use IANA TZDB and where it's needed.
    - [ ] Stand-Alone TimeZone Format
        - [ ] #TBD Design Components Bag for TimeZoneFormat
        - [ ] #622
    - [ ] CLDR Identifiers
        - [ ] #606
            - [ ] #562
        - [ ] #TBD Use short metazone identifiers
            - [ ] #561
    - [ ] TimeZone Calculations
        - [ ] #533

## Questions to Consider

- How should we determine which version of IANA TimeZone data to use?
    > "Thus the TZ data is continually being augmented. Any two implementations using the same version of the TZ data will get the same results for the same IDs (assuming a correct implementation). However, if implementations use different versions of the data they may get different results. So if precise results are required then both the TZ ID and the TZ data version must be transmitted between the different implementations."

- Will users be allowed to pass in `ZonedDateTimeInput` objects to directly to our API, or will we require them to provide a timestamp + time zone from which we will calculate the `ZonedDateTimeInput`?
    - If the former, should we validate their data, or format it regardless?

- What does this mean, and how example should we handle it?
    > "The `commonlyUsed` element is now deprecated. The CLDR committee has found it nearly impossible to obtain accurate and reliable data regarding which time zone abbreviations may be understood in a given territory, and therefore has changed to a simpler approach. Thus, if the short metazone form is available in a given locale, it is to be used for formatting regardless of the value of `commonlyUsed`. If a given short metazone form is known NOT to be understood in a given locale and the parent locale has this value such that it would normally be inherited, the inheritance of this value can be explicitly disabled by use of the 'no inheritance marker' as the value, which is 3 simultaneous empty set characters ( U+2205 )."

- How should we handle regionFormat and fallbackFormat when languages require grammatical changes during composition? Is this already handled by CLDR?
    > "Note: If a language does require grammatical changes when composing strings, then the regionFormat should either use a neutral format such as "Heure: {0}", or put all exceptional cases in explicitly translated strings."

**Comment by sffc** [comment]
@nekevss is looking at Jiff, first it tries the OS, then it goes to the bundle.

I think we should try to use environment data. I would prefer not to own it but it is deeply integrated. Maybe we could start with defering users to a third-party crate. As long as we can get the time zone ID, the offset, and the zone variant (standard/daylight), we should have all the information we need. Then we don't need to block on the work of @leftmostcat and @nordzilla, but we can still continue developing in that direction to offer clients a more complete package.
